#include "HandlePDO.h"

ZEND_NAMED_FUNCTION(handle_pdo___construct) {
	AIKIDO_METHOD_HANDLER_START();
	AIKIDO_METHOD_HANDLER_END();
}

ZEND_NAMED_FUNCTION(handle_pdo_query) {
	AIKIDO_METHOD_HANDLER_START();
	AIKIDO_METHOD_HANDLER_END();
}
