#!/bin/bash

VERSION="1.9.0"

declare -A php_api_versions

php_api_versions=(
    ["8.1"]="20210902"
)

# Find all installed PHP versions
PHP_VERSIONS=$(ls /etc/php)
for PHP_VERSION in $PHP_VERSIONS; do
    PHP_API_VERSION=${php_api_versions[$PHP_VERSION]}
    EXT_DIR="/usr/lib/php/$PHP_API_VERSION"
    if [ -d "$EXT_DIR" ]; then
        # Install PHP extension
        echo "Installing Aikido extension for PHP $PHP_VERSION (API VERSION $PHP_API_VERSION)..."
        if [ -f "/opt/aikido/aikido-$VERSION-extension-php-$PHP_VERSION.so" ]; then
            echo "Installing Aikido extension in $EXT_DIR/aikido.so"
            ln -sf /opt/aikido/aikido-$VERSION-extension-php-$PHP_VERSION.so $EXT_DIR/aikido.so
        else
            echo "Extension file /opt/aikido/aikido-$VERSION-extension-php-$PHP_VERSION.so does not exist. Skipping."
        fi

        # Installing Aikido mod
        MOD_PATHS=(
            "/etc/php/$PHP_VERSION/mods-available"
            "/etc/php/$PHP_VERSION/cli/conf.d"
            "/etc/php/$PHP_VERSION/apache2/conf.d"
        )

        for MOD_PATH in "${MOD_PATHS[@]}"; do
            if [ -d "$MOD_PATH" ]; then
                if [[ "$MOD_PATH" == *"conf.d"* ]]; then
                    echo "Installing Aikido mod in $MOD_PATH/50-aikido.ini..."
                    ln -sf /opt/aikido/aikido-dev.ini $MOD_PATH/50-aikido.ini
                else
                    echo "Installing Aikido mod in $MOD_PATH/aikido.ini..."
                    ln -sf /opt/aikido/aikido-dev.ini $MOD_PATH/aikido.ini
                fi
            else
                echo "Mod path $MOD_PATH does not exist for PHP $PHP_VERSION. Skipping."
            fi
        done
    else
        echo "PHP extension directory $EXT_DIR does not exist for PHP $PHP_VERSION. Skipping."
    fi
done

echo "Installing Aikido agent $VERSION..."
if [ -f "/opt/aikido/aikido-$VERSION" ]; then
    ln -sf /opt/aikido/aikido-$VERSION /opt/aikido/aikido
else
    echo "Aikido agent directory /opt/aikido/aikido-$VERSION does not exist. Exiting."
    exit 1
fi

echo "Registering Aikido agent to run as service..."
if command -v update-rc.d &> /dev/null; then
    update-rc.d aikido defaults
else
    echo "update-rc.d not found. Cannot register service."
    exit 1
fi

echo "Starting Aikido agent service..."
if [ -x "/etc/init.d/aikido" ]; then
    /etc/init.d/aikido start
else
    echo "Service script /etc/init.d/aikido not found. Cannot start service."
    exit 1
fi

exit 0
