#!/bin/bash

echo "Starting the uninstallation process for Aikido..."

# Function to handle script termination
cleanup() {
    echo "Uninstallation script was terminated unexpectedly."
    exit 1
}

# Trap termination signals
trap cleanup SIGTERM SIGINT

# Stop the service if it is running
if [ -e /etc/init.d/aikido ]; then
    echo "Stopping the Aikido service..."
    /etc/init.d/aikido stop || true
else
    echo "Aikido service is not running or does not exist."
fi

sleep 10

echo "Disabling the Aikido service..."
update-rc.d -f aikido remove

# Unlink the main executable if it exists
if [ -L /opt/aikido/aikido ]; then
    echo "Unlinking the Aikido main executable..."
    unlink /opt/aikido/aikido
else
    echo "Aikido main executable not found. Skipping unlink step."
fi

declare -A php_api_versions

php_api_versions=(
    ["8.1"]="20210902"
)

# Remove the PHP extension
if [ -d /etc/php ]; then
    echo "Removing the Aikido PHP extension..."
    PHP_VERSIONS=$(ls /etc/php)
    for PHP_VERSION in $PHP_VERSIONS; do
        PHP_API_VERSION=${php_api_versions[$PHP_VERSION]}
        EXT_DIR="/usr/lib/php/$PHP_API_VERSION"
        if [ -d "$EXT_DIR" ]; then
            echo "Uninstalling Aikido extension for PHP $PHP_VERSION (API VERSION $PHP_API_VERSION)..."
            if [ -L "$EXT_DIR/aikido.so" ]; then
                echo "Uninstalling Aikido extension from $EXT_DIR/aikido.so..."
                unlink $EXT_DIR/aikido.so
            else
                echo "Aikido extension not found for PHP $PHP_VERSION."
            fi
        else
            echo "PHP extension directory $EXT_DIR does not exist for PHP $PHP_VERSION. Skipping."
            continue
        fi

        # Uninstalling Aikido mod
        MOD_PATHS=(
            "/etc/php/$PHP_VERSION/mods-available"
            "/etc/php/$PHP_VERSION/cli/conf.d"
            "/etc/php/$PHP_VERSION/apache2/conf.d"
        )

        for MOD_PATH in "${MOD_PATHS[@]}"; do
            if [ -d "$MOD_PATH" ]; then
                if [[ "$MOD_PATH" == *"conf.d"* ]]; then
                    echo "Uninstalling Aikido mod from $MOD_PATH/20-aikido.ini..."
                    rm -f $MOD_PATH/20-aikido.ini
                else
                    echo "Uninstalling Aikido mod from $MOD_PATH/aikido.ini..."
                    rm -f $MOD_PATH/aikido.ini
                fi
            else
                echo "Mod path $MOD_PATH does not exist for PHP $PHP_VERSION. Skipping."
            fi
        done
    done
else
    echo "/etc/php directory not found. Skipping PHP extension removal."
fi

# Remove the Aikido log file
if [ -e "/var/log/aikido.log" ]; then
    echo "Removing /var/log/aikido.log..."
    rm -f /var/log/aikido.log
else
    echo "/var/log/aikido.log does not exist. Skipping."
fi

echo "Uninstallation process for Aikido completed."

exit 0
