#!/bin/bash
# /etc/init.d/aikido

SERVICE_NAME="aikido"

stop_service() {
    # Check if the process is running
    if pgrep -x "$SERVICE_NAME" > /dev/null; then
        echo "Stopping $SERVICE_NAME service..."
        # Attempt to stop the service using pkill
        pkill -x "$SERVICE_NAME"
        # Optionally, add a sleep to wait for the process to stop completely
        sleep 2
        # Verify the process has stopped
        if pgrep -x "$SERVICE_NAME" > /dev/null; then
            echo "Failed to stop $SERVICE_NAME service" >&2
            exit 1
        else
            echo "$SERVICE_NAME service stopped successfully"
        fi
    else
        echo "$SERVICE_NAME service is not running"
    fi
}

case "$1" in
  start)
    echo "Starting aikido"
    /opt/aikido/aikido &
    ;;
  stop)
    echo "Stopping aikido"
    stop_service
    ;;
  restart)
    $0 stop
    $0 start
    ;;
  *)
    echo "Usage: /etc/init.d/aikido {start|stop|restart}"
    exit 1
    ;;
esac

exit 0
